export const PHONE_MODELS: string[] = [
  // Apple iPhone (2016–2025)
  "iPhone 6s",
  "iPhone 6s Plus",
  "iPhone 7",
  "iPhone 7 Plus",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X",
  "iPhone XR",
  "iPhone XS",
  "iPhone XS Max",
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPhone SE (2nd gen)",
  "iPhone SE (3rd gen)",
  "iPhone 12",
  "iPhone 12 mini",
  "iPhone 12 Pro",
  "iPhone 12 Pro Max",
  "iPhone 13",
  "iPhone 13 mini",
  "iPhone 13 Pro",
  "iPhone 13 Pro Max",
  "iPhone 14",
  "iPhone 14 Plus",
  "iPhone 14 Pro",
  "iPhone 14 Pro Max",
  "iPhone 15",
  "iPhone 15 Plus",
  "iPhone 15 Pro",
  "iPhone 15 Pro Max",
  "iPhone 16",
  "iPhone 16 Pro",
  "iPhone 16 Pro Max",
  "iPhone 17",
  "iPhone 17 Pro",
  "iPhone 17 Pro Max",

  // Samsung Galaxy S (flagship)
  "Samsung Galaxy S8",
  "Samsung Galaxy S8+",
  "Samsung Galaxy S9",
  "Samsung Galaxy S9+",
  "Samsung Galaxy S10",
  "Samsung Galaxy S10+",
  "Samsung Galaxy S10e",
  "Samsung Galaxy S20",
  "Samsung Galaxy S20+",
  "Samsung Galaxy S20 Ultra",
  "Samsung Galaxy S21",
  "Samsung Galaxy S21+",
  "Samsung Galaxy S21 Ultra",
  "Samsung Galaxy S22",
  "Samsung Galaxy S22+",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy S23",
  "Samsung Galaxy S23+",
  "Samsung Galaxy S23 Ultra",
  "Samsung Galaxy S24",
  "Samsung Galaxy S24+",
  "Samsung Galaxy S24 Ultra",
  "Samsung Galaxy S25",
  "Samsung Galaxy S25+",
  "Samsung Galaxy S25 Ultra",

  // Samsung Galaxy Note (discontinued)
  "Samsung Galaxy Note 8",
  "Samsung Galaxy Note 9",
  "Samsung Galaxy Note 10",
  "Samsung Galaxy Note 10+",
  "Samsung Galaxy Note 20",
  "Samsung Galaxy Note 20 Ultra",

  // Samsung Galaxy Z (foldables)
  "Samsung Galaxy Z Fold2",
  "Samsung Galaxy Z Fold3",
  "Samsung Galaxy Z Fold4",
  "Samsung Galaxy Z Fold5",
  "Samsung Galaxy Z Fold6",
  "Samsung Galaxy Z Fold7",
  "Samsung Galaxy Z Flip3",
  "Samsung Galaxy Z Flip4",
  "Samsung Galaxy Z Flip5",
  "Samsung Galaxy Z Flip6",
  "Samsung Galaxy Z Flip7",

  // Samsung Galaxy A (mid-range)
  "Samsung Galaxy A50",
  "Samsung Galaxy A51",
  "Samsung Galaxy A52",
  "Samsung Galaxy A53",
  "Samsung Galaxy A54",
  "Samsung Galaxy A55",
  "Samsung Galaxy A56 5G",
  "Samsung Galaxy A34",

  // Samsung Galaxy M (mid-range)
  "Samsung Galaxy M34",
  "Samsung Galaxy M54",

  // Google Pixel (flagship)
  "Google Pixel 1",
  "Google Pixel XL",
  "Google Pixel 2",
  "Google Pixel 2 XL",
  "Google Pixel 3",
  "Google Pixel 3 XL",
  "Google Pixel 3a",
  "Google Pixel 3a XL",
  "Google Pixel 4",
  "Google Pixel 4 XL",
  "Google Pixel 4a",
  "Google Pixel 4a 5G",
  "Google Pixel 5",
  "Google Pixel 5a",
  "Google Pixel 6",
  "Google Pixel 6 Pro",
  "Google Pixel 6a",
  "Google Pixel 7",
  "Google Pixel 7 Pro",
  "Google Pixel 7a",
  "Google Pixel 8",
  "Google Pixel 8 Pro",
  "Google Pixel 8a",
  "Google Pixel 9",
  "Google Pixel 9 Pro",
  "Google Pixel 9 Pro XL",
  "Google Pixel Fold",
  "Google Pixel 9 Pro Fold",

  // OPPO Find / Reno / A
  "OPPO Find X",
  "OPPO Find X2 Pro",
  "OPPO Find X3 Pro",
  "OPPO Find X5 Pro",
  "OPPO Find X6 Pro",
  "OPPO Find X7 Ultra",
  "OPPO Find X9 Pro",
  "OPPO Find N",
  "OPPO Find N2 Flip",
  "OPPO Find N3",
  "OPPO Find N4",
  "OPPO Reno 5",
  "OPPO Reno 6 Pro",
  "OPPO Reno 7",
  "OPPO Reno 8",
  "OPPO Reno 8 Pro",
  "OPPO Reno 9",
  "OPPO Reno 10 Pro 5G",
  "OPPO Reno 11",
  "OPPO Reno 11 Pro",
  "OPPO Reno 12",
  "OPPO Reno 13 F 5G",
  "OPPO A57",
  "OPPO A77",
  "OPPO A78",
  "OPPO A79",
  "OPPO A98",
  "OPPO A38",
  "OPPO A5 Pro 5G",

  // Xiaomi (Mi / Xiaomi)
  "Xiaomi Mi 8",
  "Xiaomi Mi 9",
  "Xiaomi Mi 10",
  "Xiaomi Mi 10T",
  "Xiaomi Mi 11",
  "Xiaomi 12",
  "Xiaomi 12 Pro",
  "Xiaomi 13",
  "Xiaomi 13 Pro",
  "Xiaomi 13 Ultra",
  "Xiaomi 14",
  "Xiaomi 14 Pro",
  "Xiaomi 14 Ultra",
  "Xiaomi 15",
  "Xiaomi 15 Pro",
  "Xiaomi 15 Ultra",

  // Redmi Note
  "Redmi Note 7",
  "Redmi Note 8",
  "Redmi Note 8 Pro",
  "Redmi Note 9",
  "Redmi Note 9 Pro",
  "Redmi Note 10",
  "Redmi Note 10 Pro",
  "Redmi Note 11",
  "Redmi Note 11 Pro",
  "Redmi Note 12",
  "Redmi Note 12 Pro",
  "Redmi Note 13",
  "Redmi Note 13 Pro",
  "Redmi Note 14",
  "Redmi Note 14 Pro",

  // POCO (performance)
  "POCO F1",
  "POCO F2 Pro",
  "POCO F3",
  "POCO F4",
  "POCO F5",
  "POCO F5 Pro",
  "POCO F6",
  "POCO F6 Pro",
  "POCO X3",
  "POCO X3 Pro",
  "POCO X4 Pro",
  "POCO X5 Pro",
  "POCO X6",
  "POCO M3",
  "POCO M4 Pro",
  "POCO M5",

  // Motorola Moto / Edge / Razr / E
  "Motorola Moto G4",
  "Motorola Moto G5",
  "Motorola Moto G5 Plus",
  "Motorola Moto G6",
  "Motorola Moto G6 Plus",
  "Motorola Moto G7",
  "Motorola Moto G7 Plus",
  "Motorola Moto G8",
  "Motorola Moto G9",
  "Motorola Moto G31",
  "Motorola Moto G32",
  "Motorola Moto G53",
  "Motorola Moto G54",
  "Motorola Moto G84",
  "Motorola Edge",
  "Motorola Edge+",
  "Motorola Edge 20 Pro",
  "Motorola Edge 30 Pro",
  "Motorola Edge 40",
  "Motorola Edge 40 Pro",
  "Motorola Razr (2019)",
  "Motorola Razr 5G (2020)",
  "Motorola Razr 40",
  "Motorola Razr 40 Ultra",
  "Motorola Moto E4 Plus",
  "Motorola Moto E5",
  "Motorola Moto E5 Plus",
  "Motorola Moto E6",
  "Motorola Moto E7",
  "Motorola Moto E7 Plus",
  "Motorola Moto E20",
  "Motorola Moto E30",
  "Motorola Moto E40",
];
